config/routes.rb
Rails.application.routes.draw do
    root "home#root"
    get "terms-of-service", to: "home#terms_of_service", as: "terms_of_service"
    get "privacy-policy", to: "home#privacy_policy", as: "privacy_policy"
    get "security-policy", to: "home#security_policy", as: "security_policy"
    get "sponsors", to: "home#sponsors", as: "sponsors"

    get "search", to: "home#search", as: "search"

    # User routes
    get "user/:username", to: "user/user#public", as: "user_public"

    scope :account do
        get "/", to: "user/user#show", as: "user"
        get "edit", to: "user/user#edit", as: "user_edit"
        patch "edit", to: "user/user#update"

        get "quizzes", to: "user/user#quizzes", as: "user_quizzes"
        get "favorites", to: "user/user#favorites", as: "user_favorites"
        get "library", to: "user/user#library", as: "user_library"

        get "settings", to: "user/user#settings", as: "user_settings"
        patch "settings", to: "user/user#update_settings"

        get "delete(/:destroy_token)",
            to: "user/user#request_destroy",
            as: "user_delete"
        delete "delete/:destroy_token", to: "user/user#destroy"
    end

    scope :password do
        get "reset", to: "user/password#reset", as: "user_password_reset"
        post "reset", to: "user/password#send_email"

        get "edit/:password_reset_token",
            to: "user/password#edit",
            as: "user_password_edit"
        post "edit/:password_reset_token", to: "user/password#update"
    end

    scope :verify do
        get "/", to: "user/verification#success", as: "user_verification_success"
        get "send", to: "user/verification#send_email", as: "user_verification_send"
        get "pending",
            to: "user/verification#pending",
            as: "user_verification_pending"
        get ":verification_token", to: "user/verification#verify", as: "user_verify"
    end

    patch "language", to: "user/user#change_lang", as: "change_language"

    get "signup", to: "user/user#new", as: "user_create"
    post "signup", to: "user/user#create"

    get "login", to: "user/sessions#new", as: "user_login"
    post "login", to: "user/sessions#create"

    get "logout", to: "user/sessions#destroy", as: "user_logout"

    # Quiz routes
    namespace :quiz do
        get "create", to: "quiz#new", as: "create"
        post "create", to: "quiz#create"

        scope ":quiz_uuid" do
            get "/", to: "quiz#show", as: "show"
            get "edit", to: "quiz#edit", as: "edit"
            patch "edit", to: "quiz#update"
            get "delete", to: "quiz#request_destroy", as: "request_destroy"
            delete "delete/:destroy_token", to: "quiz#destroy", as: "delete"

            patch "favorite", to: "quiz#favorite", as: "favorite"

            get "cards", to: "quiz#cards", as: "cards"
            get "write", to: "quiz#write", as: "write"
            get "multi", to: "quiz#multi", as: "multi"
            get "smart", to: "quiz#smart", as: "smart"

            get "report", to: "quiz#new_report", as: "report"
            post "report", to: "quiz#report"
        end
    end

    # Bug report routes
    post "report", to: "admin/bug_report#create", as: "bug_report"

    # API routes
    namespace :api do
        defaults format: :json do
            scope :user do
                get "username/validate/:username", to: "user#username_validator", as: "username_validator"
                put "create", to: "user#create", as: "user_create"
                post "login", to: "user#login", as: "user_login"
                post "refresh", to: "user#refresh_token", as: "user_refresh_token"

                get "search(/:page)", to: "user#search", as: "user_search"

                get "quizzes(/:page)", to: "user#quizzes", as: "user_quizzes"
                get "favorites(/:page)", to: "user#favorites", as: "user_favorites"
                get ":username/public(/:page)", to: "user#public", as: "user_public"

                get "delete_token", to: "user#request_delete_token", as: "user_request_delete"
                delete "delete/:destroy_token", to: "user#destroy", as: "user_destroy"

                patch "update", to: "user#update", as: "user_update"
                patch "settings", to: "user#update_settings", as: "user_update_settings"

                get "data", to: "user#data", as: "user_data"
            end

            scope :quiz do
                put "create", to: "quiz#create", as: "quiz_create"

                get "search(/:page)", to: "quiz#search", as: "quiz_search"

                scope ":quiz_id" do
                    get "data", to: "quiz#data", as: "quiz_data"

                    post "report", to: "quiz#report", as: "quiz_report"

                    patch "update", to: "quiz#update", as: "quiz_update"
                    patch "favorite", to: "quiz#favorite_quiz", as: "quiz_favorite"

                    scope :score do
                        patch "sync", to: "quiz#sync_score", as: "quiz_sync_score"
                        patch "reset/:mode", to: "quiz#reset_score", as: "quiz_reset_score"
                        patch ":score_id/favorite", to: "quiz#favorite", as: "quiz_favorite_score"
                        patch ":score_id/:mode", to: "quiz#score", as: "quiz_score"
                    end

                    get "delete_token", to: "quiz#request_destroy", as: "quiz_request_delete"
                    delete "delete/:destroy_token", to: "quiz#destroy", as: "quiz_delete"
                end
            end

            get "languages", to: "api#languages"

            put "bug/create", to: "bug_report#create"
        end

        scope :docs do
            get "/", to: "docs#index", as: "docs"
            get "users", to: "docs#users", as: "docs_users"
            get "quizzes", to: "docs#quizzes", as: "docs_quizzes"
            get "authentication", to: "docs#authentication", as: "docs_authentication"
            get "errors", to: "docs#general_errors", as: "docs_general_errors"
            get "bugs", to: "docs#bugs", as: "docs_bugs"
            get "languages", to: "docs#languages", as: "docs_languages"
        end
    end

    # Admin routes
    namespace :admin do
        get "users", to: "users#index", as: "users"

        get "ban_ip", to: "users#ban_ip_form", as: "ban_ip"
        put "ban_ip", to: "users#ban_ip"
        delete "ban_ip", to: "users#unban_ip"

        scope :bugs do
            scope :triage do
                get "/", to: "bug_report#triage", as: "bug_triage"
                get ":bug_report_id", to: "bug_report#triage_show", as: "bug_triage_show"
                patch ":bug_report_id", to: "bug_report#triage_verdict"
            end

            get "list", to: "bug_report#list", as: "bugs"

            scope ":bug_id" do
                get "/", to: "bug_report#show", as: "bug"
                patch "status", to: "bug_report#status", as: "bug_status"
            end
        end

        scope :transactions do
            get "/", to: "transaction#list", as: "transactions"
            get "removed", to: "transaction#removed", as: "removed_transactions"

            get "create", to: "transaction#new", as: "new_transaction"
            post "create", to: "transaction#create"

            scope ":transaction_id" do
                get "/", to: "transaction#show", as: "show_transaction"

                delete "delete", to: "transaction#delete", as: "delete_transaction"
                patch "restore", to: "transaction#restore", as: "restore_transaction"
            end
        end

        scope :user do
            scope ":username" do
                get "delete(/:destroy_token)",
                    to: "users#destroy_token",
                    as: "user_delete"
                delete "delete/:destroy_token", to: "users#destroy"

                get "ban", to: "users#ban_form", as: "user_ban"
                patch "ban", to: "users#ban"
                patch "unban", to: "users#unban", as: "user_unban"
            end

            scope "edit/:username" do
                get "/", to: "users#edit", as: "user_edit"
                patch "/", to: "users#update"
            end

            scope ":username/send" do
                get "verification",
                    to: "users#send_verification",
                    as: "user_send_verification"
                get "reset",
                    to: "users#send_password_reset",
                    as: "user_send_password_reset"
                get "email", to: "users#prepare_email", as: "user_send_email"
                post "email", to: "users#send_email"
            end
        end

        get "quiz/report/:quiz_report_id", to: "quiz#show_report", as: "quiz_report"
        get "quiz/triage", to: "quiz#triage", as: "quiz_report_triage"
        post "quiz/triage/:triage_id/ignore", to: "quiz#ignore_triage", as: "quiz_report_ignore_triage"
        scope "quiz/:quiz_id" do
            get "edit", to: "quiz#edit", as: "quiz_edit"
            post "edit", to: "quiz#update", as: "quiz_update"
            get "delete", to: "quiz#request_destroy", as: "quiz_request_delete"
            delete "delete/:delete_token", to: "quiz#destroy", as: "quiz_delete"
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action { setup_locale "home" }

    def search
        results = Quiz.search_all_quizzes params
        @quizzes = results.first
        @pages = results.last
        @params = quiz_search_params
    end

    def root
        @new_quizzes = Quiz.where(visibility: "public").order(created_at: :desc).limit(5)

        return unless logged_in?

        @quizzes = @user.quizzes.order(created_at: :desc).limit(5)
    end

    def sponsors; end

    def terms_of_service
        @title = "Terms of Service | Freequiz"
    end

    def privacy_policy
        @title = "Privacy Policy | Freequiz"
    end

    def security_policy
        @title = "Security Policy | Freequiz"
    end

    private

    def quiz_search_params
        params.permit(:title, :sort, :commit, :page)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_language_button.html.erb
<%= form_with url: change_language_path, method: :patch, class: "border-b border-s sm:border-t border-e sm:border-e-0 first:border-t sm:first:rounded-l sm:first:rounded-e-none sm:last:rounded-l-none sm:last:rounded-r first:rounded-t last:rounded-b last:border-e dark:border-gray-700 #{"bg-blue-700 border-blue-700 text-white" if I18n.locale == locale.to_sym}" do |form| %>
    <%= form.text_field :return_to, hidden: true, value: request.path %>
    <%= form.text_field :locale, hidden: true, value: locale %>
    <%= form.button type: :submit, class: "flex items-center justify-between sm:justify-normal gap-2 px-1 sm:px-4 py-1 w-full" do  %>
        <%= image_tag "flags/#{locale}.jpg", class: "h-6 rounded" %>
        <%= tg "languages.#{locale}" %>
        <%= image_tag "flags/#{locale}.jpg", class: "h-6 rounded block sm:hidden" %>
    <% end %>
<% end %>

app/views/home/apple_association.json.erb
{
    "applinks": {
        "apps": [

        ],
        "details": [
            {
                "appID": "RATUG9FJKL.com.freequiz.freequiz",
                "paths": [
                    "NOT /admin/*",
                    "NOT /api/*",
                    "NOT /verify",
                    "NOT /verify/*",
                    "NOT /bugs/*",
                    "*"
                ]
            }
        ]
    }
}

app/views/home/privacy_policy.html.erb
<h1>Privacy Policy</h1>

<p class="my-2">This privacy policy was last updated on August 20, 2024</p>

<p class="my-2">For simplicity's sake and to avoid translation errors the <%= link_to "Terms of Service", terms_of_service_path %>, <%= link_to "Privacy Policy", privacy_policy_path %> and <%= link_to "Security Policy", security_policy_path %> are only available in English.</p>

<p class="mt-5 mb-2">Thanks for trusting Freequiz ('Freequiz', 'we', 'us', 'our') with your personal information! We take our responsibility to you very seriously, and so this Privacy Statement describes how we handle your data.</p>

<p class="my-2">This Privacy Statement applies to all websites we own and operate and to all services we provide (collectively, the 'Services'). So...PLEASE READ THIS PRIVACY STATEMENT CAREFULLY. By using the Services, you are expressly and voluntarily accepting the terms and conditions of this Privacy Statement and our Terms of Service, which include allowing us to process information about you.</p>

<p class="my-2">Under this Privacy Statement, we are the data controller responsible for processing your personal information. Our contact information appears at the end of this Privacy Statement.</p>

<h2 class="text-start mt-5">What data do we collect?</h2>

<p class="my-2">Freequiz collects the following data:</p>

<ul class="ms-10 list-disc">
    <li>Email</li>
    <li>Username</li>
    <li>Data about your last two logins including login date, IP address, assumed location of the IP address provided by <a href="https://ipwhois.io/">IPWHOIS.IO</a></li>
    <li>Your currently active settings</li>
    <li>Data about Quizzes you create</li>
    <li>Score data of Quizzes you learn</li>
    <li>Data you provide in bug reports</li>
    <li>Data you provide in Quiz reports</li>
</ul>

<p class="mt-5 mb-2">If you believe a certain data type is missing from the lists above, feel free to contact us and we will answer any questions and update the privacy policy.</p>

<h2 class="text-start mt-5">How do we collect your data?</h2>

<p class="my-2">You directly provide most of the data we collect or collected data is computed from certain actions on our Services. We collect data and process data when you:</p>

<ul class="ms-10 list-disc">
    <li>Create an account</li>
    <li>Sign in to your account</li>
    <li>Change your settings</li>
    <li>Learn a quiz</li>
    <li>Submit a bug report</li>
    <li>Submit a quiz report</li>
</ul>

<h2 class="text-start mt-5">How will we use your data?</h2>

<p class="my-2">Freequiz collects your data so that we can:</p>

<ul class="ms-10 list-disc">
    <li>Identify you on the website</li>
    <li>Allow you to edit the content generated by you</li>
    <li>Save your progress on learning Quizzes</li>
    <li>Remember your settings</li>
    <li>Process bug reports</li>
    <li>Process quiz reports</li>
</ul>

<p class="mt-5 mb-2">If you are found to be exploiting, misusing the website or found to be violating our Terms of Service, we may prevent you from deleting your account to prevent you from creating new accounts.</p>

<h2 class="text-start mt-5">How do we store your data?</h2>

<p class="my-2">Freequiz stores your data on PostgreSQL on Heroku</p>

<h2 class="text-start mt-5">Data leaks</h2>

We do not take responsability or may be taken reponsible for data leaks caused by us or our service providers.

<h2 class="text-start mt-5">Deleting your data</h2>

<p class="my-2">You are entitled for all your personal data or content generated by you to be removed from our database with the following exceptions:</p>

<ul class="ms-10 list-disc">
    <li>Bug reports you created can not be removed as they may affect the integrity of the website.</li>
    <li>Quiz reports you created can not be removed as they may affect other Users security, right to privacy and compliance to our Terms of Service.</li>
    <li>If you are found to violate our Terms of Service we may prevent you from deleting your account to prevent you from creating new accounts.</li>
</ul>

<h2 class="text-start mt-5">What are your data protection rights?</h2>

<p class="my-2">Freequiz would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following:</p>

<ul class="ms-10 list-disc">
    <li>The right to access – You have the right to request Freequiz for copies of your personal data. We may limit the number of times this request can be made depending on the size of the request.</li>
    <li>The right to rectification – You have the right to request that Freequiz correct any information you believe is inaccurate. You also have the right to request Freequiz to complete the information you believe is incomplete.</li>
    <li>The right to erasure – You have the right to request that Freequiz erase your personal data, under certain conditions. (Conditions are listed in the "Deleting your data" section)</li>
    <li>The right to restrict processing – You have the right to request that Freequiz restrict the processing of your personal data, under certain conditions.</li>
    <li>The right to object to processing – You have the right to object to Freequiz processing of your personal data, under certain conditions.</li>
    <li>The right to data portability – You have the right to request that Freequiz transfer the data that we have collected to another organization, or directly to you, under certain conditions.</li>
</ul>

<h2 class="text-start mt-5">What log data do we collect?</h2>

<p class="my-2">Like most websites, Freequiz collects information that your browser sends whenever you visit the website. This data may include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and time spent on each page. THIS DATA DOES NOT CONTAIN ANY PERSONALLY IDENTIFIABLE INFORMATION. We use this information for analyzing trends, administering the site, tracking users' movement on the website, and gathering demographic information.</p>

<p class="my-2">In our case, this service is provided by Google Analytics.</p>

<h2 class="text-start mt-5">What are cookies?</h2>

<p class="my-2">Cookies are text files placed on your computer to collect standard Internet log information and visitor behavior information. When you visit our websites, we may collect information from you automatically through cookies or similar technology.</p>

<p class="my-2">For further information, see <a href="https://en.wikipedia.org/wiki/HTTP_cookie">HTTP cookie</a> on Wikipedia.</p>

<h2 class="text-start mt-5">How do we use cookies?</h2>

<p class="my-2">Freequiz uses cookies in a range of ways to improve your experience on our website, including:</p>

<ul class="ms-10 list-disc">
    <li>Keeping you signed in</li>
    <li>Remembering your active settings</li>
</ul>

<h2 class="text-start mt-5">What types of cookies do we use?</h2>

<p class="my-2">There are a number of different types of cookies; however, our website uses functionality cookies. Freequiz uses these cookies so we recognize you on our website and remember your previously selected settings.</p>

<h2 class="text-start mt-5">How to manage your cookies</h2>

<p class="my-2">You can set your browser not to accept cookies. However, in a few cases, some of our website features may behave unexpectedly or fail to function as a result.</p>

<h2 class="text-start mt-5">Privacy policies of other websites</h2>

<p class="my-2">Freequiz contains links to other external websites. <strong>Our privacy policy only applies to our website, so if you click on a link to another website, you should read their privacy policy.</strong></p>

<h2 class="text-start mt-5">Changes to our privacy policy</h2>

<p class="my-2">Freequiz keeps its privacy policy under regular review and places any updates on this web page. The Freequiz privacy policy may be subject to change at any given time without notice.</p>

<h2 class="text-start mt-5">How to contact us</h2>

<p class="my-2">If you have any questions about Freequiz's privacy policy, the data we hold on you, or you would like to exercise one of your data protection rights, please do not hesitate to contact us.</p>

<p class="mt-5 mb-2">Email: <a href="mailto:info@freequiz.ch">info@freequiz.ch</a></p>

<p class="mt-5">Privacy Policy based on <a href="https://monkeytype.com/privacy-policy">Monkeytypes privacy policy</a></p>

app/views/home/root.html.erb
<h1 data-test-id="root-welcome">
    <% if logged_in? %>
        <%= t ".welcome_name", username: @user.username %>
    <% else %>
        <%= tl "welcome" %>
    <% end %>
</h1>

<% unless logged_in? %>
    <div class="flex justify-center">
        <div class="flex flex-col gap-2 max-w-xl w-full">
            <div class="flex flex-col sm:flex-row justify-center">
                <% Setting::LOCALES.each do |locale| %>
                    <%= render partial: "language_button", locals: { locale: } %>
                <% end %>
            </div>
            <div class="flex flex-col sm:flex-row gap-2">
                <%= link_to tg("login"), user_login_path, class: "btn-primary grow basis-0" %>
                <%= link_to tg("create_account"), user_create_path, class: "btn-primary grow basis-0" %>
            </div>
        </div>
    </div>
<% else %>
    <% if @user.admin? %>
        <h3 class="mt-5"><%= t ".admin" %></h3>
        <div class="mb-5 flex flex-col sm:flex-row gap-2 align-center">
            <%= link_to "Bug Triage (#{BugReport.where(status: :new).count})", admin_bug_triage_path, class: "btn-primary text-xl basis-0 grow" %>
            <%= link_to "Quiz triage (#{QuizReport.where(status: :open).count})", admin_quiz_report_triage_path, class: "btn-primary text-xl basis-0 grow" %>
        </div>
    <% end %>

    <h3><%= t ".what_do" %></h3>
    <div class="flex flex-col md:flex-row gap-2 align-center">
        <%= link_to t(".create_quiz"), quiz_create_path, class: "btn-success text-xl basis-0 grow" %>
        <%= link_to t(".view_account"), user_path, class: "btn-primary text-xl basis-0 grow" %>
        <%= link_to t(".view_favorites"), user_favorites_path, class: "btn-primary text-xl basis-0 grow" %>
        <%= link_to t(".own_quizzes"), user_quizzes_path, class: "btn-primary text-xl basis-0 grow" %>
    </div>

    <h3 class="mt-5"><%= t ".your_quizzes" %></h3>
    <%= render partial: "partials/quiz_list", locals: { quizzes: @quizzes, no_username: true } %>
<% end %>

<h3 class="mt-5"><%= t ".new_quizzes" %></h3>
<%= render partial: "partials/quiz_list", locals: { quizzes: @new_quizzes } %>

app/views/home/search.html.erb
<h1><%= tp "search" %></h1>

<%= render partial: "partials/quiz_search", locals: { url: search_path } %>
<%= render partial: "partials/quiz_list", locals: { quizzes: @quizzes } %>
<br>
<%= render partial: "partials/page_navigator", locals: { pages: @pages, params: @params } %>

app/views/home/security_policy.html.erb
<h1>Security Policy</h1>

<p class="my-2">This security policy was last updated on August 20, 2024</p>

<p class="my-2">For simplicity's sake and to avoid translation errors the <%= link_to "Terms of Service", terms_of_service_path %>, <%= link_to "Privacy Policy", privacy_policy_path %> and <%= link_to "Security Policy", security_policy_path %> are only available in English.</p>

<p class="mt-5 mb-2">We take the security and integrity of Freequiz very seriously. If you have found a vulnerability, please report it ASAP so we can quickly remediate the issue.</p>

<h2 class="text-start mt-5">How to Disclose a Vulnerability</h2>

<p class="my-2">For vulnerabilities that impact the confidentiality, integrity, and availability of Freequiz services, please send your disclosure via <a href="mailto:info@freequiz.ch">email</a>. For non-security related platform bugs use our bug submission menu available in your account tab in the navigation bar.</p>

<h2 class="text-start mt-5">Submission Guidelines</h2>

<p class="my-2">Do not engage in activities that might cause a denial of service condition, create significant strains on critical resources, or negatively impact users of the site outside of test accounts.</p>

<p class="mt-5">Security Policy based on <a href="https://monkeytype.com/security-policy">Monkeytypes security policy</a></p>

app/views/home/sponsors.html.erb
<ul>
    <li>Physiotherapie Grabenstätter - Teichweg 9, 4450 Sissach</li>
    <li>Senta Fischer</li>
</ul>