config/routes.rb
Rails.application.routes.draw do
    root "home#root"
    get "terms-of-service", to: "home#terms_of_service", as: "terms_of_service"
    get "privacy-policy", to: "home#privacy_policy", as: "privacy_policy"
    get "security-policy", to: "home#security_policy", as: "security_policy"
    get "sponsors", to: "home#sponsors", as: "sponsors"

    get "search", to: "home#search", as: "search"

    # User routes
    get "user/:username", to: "user/user#public", as: "user_public"

    scope :account do
        get "/", to: "user/user#show", as: "user"
        get "edit", to: "user/user#edit", as: "user_edit"
        patch "edit", to: "user/user#update"

        get "quizzes", to: "user/user#quizzes", as: "user_quizzes"
        get "favorites", to: "user/user#favorites", as: "user_favorites"
        get "library", to: "user/user#library", as: "user_library"

        get "settings", to: "user/user#settings", as: "user_settings"
        patch "settings", to: "user/user#update_settings"

        get "delete(/:destroy_token)",
            to: "user/user#request_destroy",
            as: "user_delete"
        delete "delete/:destroy_token", to: "user/user#destroy"
    end

    scope :password do
        get "reset", to: "user/password#reset", as: "user_password_reset"
        post "reset", to: "user/password#send_email"

        get "edit/:password_reset_token",
            to: "user/password#edit",
            as: "user_password_edit"
        post "edit/:password_reset_token", to: "user/password#update"
    end

    scope :verify do
        get "/", to: "user/verification#success", as: "user_verification_success"
        get "send", to: "user/verification#send_email", as: "user_verification_send"
        get "pending",
            to: "user/verification#pending",
            as: "user_verification_pending"
        get ":verification_token", to: "user/verification#verify", as: "user_verify"
    end

    patch "language", to: "user/user#change_lang", as: "change_language"

    get "signup", to: "user/user#new", as: "user_create"
    post "signup", to: "user/user#create"

    get "login", to: "user/sessions#new", as: "user_login"
    post "login", to: "user/sessions#create"

    get "logout", to: "user/sessions#destroy", as: "user_logout"

    # Quiz routes
    namespace :quiz do
        get "create", to: "quiz#new", as: "create"
        post "create", to: "quiz#create"

        scope ":quiz_uuid" do
            get "/", to: "quiz#show", as: "show"
            get "edit", to: "quiz#edit", as: "edit"
            patch "edit", to: "quiz#update"
            get "delete", to: "quiz#request_destroy", as: "request_destroy"
            delete "delete/:destroy_token", to: "quiz#destroy", as: "delete"

            patch "favorite", to: "quiz#favorite", as: "favorite"

            get "cards", to: "quiz#cards", as: "cards"
            get "write", to: "quiz#write", as: "write"
            get "multi", to: "quiz#multi", as: "multi"
            get "smart", to: "quiz#smart", as: "smart"

            get "report", to: "quiz#new_report", as: "report"
            post "report", to: "quiz#report"
        end
    end

    # Bug report routes
    post "report", to: "admin/bug_report#create", as: "bug_report"

    # API routes
    namespace :api do
        defaults format: :json do
            scope :user do
                get "username/validate/:username", to: "user#username_validator", as: "username_validator"
                put "create", to: "user#create", as: "user_create"
                post "login", to: "user#login", as: "user_login"
                post "refresh", to: "user#refresh_token", as: "user_refresh_token"

                get "search(/:page)", to: "user#search", as: "user_search"

                get "quizzes(/:page)", to: "user#quizzes", as: "user_quizzes"
                get "favorites(/:page)", to: "user#favorites", as: "user_favorites"
                get ":username/public(/:page)", to: "user#public", as: "user_public"

                get "delete_token", to: "user#request_delete_token", as: "user_request_delete"
                delete "delete/:destroy_token", to: "user#destroy", as: "user_destroy"

                patch "update", to: "user#update", as: "user_update"
                patch "settings", to: "user#update_settings", as: "user_update_settings"

                get "data", to: "user#data", as: "user_data"
            end

            scope :quiz do
                put "create", to: "quiz#create", as: "quiz_create"

                get "search(/:page)", to: "quiz#search", as: "quiz_search"

                scope ":quiz_id" do
                    get "data", to: "quiz#data", as: "quiz_data"

                    post "report", to: "quiz#report", as: "quiz_report"

                    patch "update", to: "quiz#update", as: "quiz_update"
                    patch "favorite", to: "quiz#favorite_quiz", as: "quiz_favorite"

                    scope :score do
                        patch "sync", to: "quiz#sync_score", as: "quiz_sync_score"
                        patch "reset/:mode", to: "quiz#reset_score", as: "quiz_reset_score"
                        patch ":score_id/favorite", to: "quiz#favorite", as: "quiz_favorite_score"
                        patch ":score_id/:mode", to: "quiz#score", as: "quiz_score"
                    end

                    get "delete_token", to: "quiz#request_destroy", as: "quiz_request_delete"
                    delete "delete/:destroy_token", to: "quiz#destroy", as: "quiz_delete"
                end
            end

            get "languages", to: "api#languages"

            put "bug/create", to: "bug_report#create"
        end

        scope :docs do
            get "/", to: "docs#index", as: "docs"
            get "users", to: "docs#users", as: "docs_users"
            get "quizzes", to: "docs#quizzes", as: "docs_quizzes"
            get "authentication", to: "docs#authentication", as: "docs_authentication"
            get "errors", to: "docs#general_errors", as: "docs_general_errors"
            get "bugs", to: "docs#bugs", as: "docs_bugs"
            get "languages", to: "docs#languages", as: "docs_languages"
        end
    end

    # Admin routes
    namespace :admin do
        get "users", to: "users#index", as: "users"

        get "ban_ip", to: "users#ban_ip_form", as: "ban_ip"
        put "ban_ip", to: "users#ban_ip"
        delete "ban_ip", to: "users#unban_ip"

        scope :bugs do
            scope :triage do
                get "/", to: "bug_report#triage", as: "bug_triage"
                get ":bug_report_id", to: "bug_report#triage_show", as: "bug_triage_show"
                patch ":bug_report_id", to: "bug_report#triage_verdict"
            end

            get "list", to: "bug_report#list", as: "bugs"

            scope ":bug_id" do
                get "/", to: "bug_report#show", as: "bug"
                patch "status", to: "bug_report#status", as: "bug_status"
            end
        end

        scope :transactions do
            get "/", to: "transaction#list", as: "transactions"
            get "removed", to: "transaction#removed", as: "removed_transactions"

            get "create", to: "transaction#new", as: "new_transaction"
            post "create", to: "transaction#create"

            scope ":transaction_id" do
                get "/", to: "transaction#show", as: "show_transaction"

                delete "delete", to: "transaction#delete", as: "delete_transaction"
                patch "restore", to: "transaction#restore", as: "restore_transaction"
            end
        end

        scope :user do
            scope ":username" do
                get "delete(/:destroy_token)",
                    to: "users#destroy_token",
                    as: "user_delete"
                delete "delete/:destroy_token", to: "users#destroy"

                get "ban", to: "users#ban_form", as: "user_ban"
                patch "ban", to: "users#ban"
                patch "unban", to: "users#unban", as: "user_unban"
            end

            scope "edit/:username" do
                get "/", to: "users#edit", as: "user_edit"
                patch "/", to: "users#update"
            end

            scope ":username/send" do
                get "verification",
                    to: "users#send_verification",
                    as: "user_send_verification"
                get "reset",
                    to: "users#send_password_reset",
                    as: "user_send_password_reset"
                get "email", to: "users#prepare_email", as: "user_send_email"
                post "email", to: "users#send_email"
            end
        end

        get "quiz/report/:quiz_report_id", to: "quiz#show_report", as: "quiz_report"
        get "quiz/triage", to: "quiz#triage", as: "quiz_report_triage"
        post "quiz/triage/:triage_id/ignore", to: "quiz#ignore_triage", as: "quiz_report_ignore_triage"
        scope "quiz/:quiz_id" do
            get "edit", to: "quiz#edit", as: "quiz_edit"
            post "edit", to: "quiz#update", as: "quiz_update"
            get "delete", to: "quiz#request_destroy", as: "quiz_request_delete"
            delete "delete/:delete_token", to: "quiz#destroy", as: "quiz_delete"
        end
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :require_admin!

    def index
        @sort_criteria = [
            ["Date created", "created_at"],
            ["Date updated", "updated_at"],
            ["Date confirmed", "confirmed_at"],
            ["Last login", "last_sign_in_at"]
        ]
        @order_criteria = [
            %w[Descending DESC],
            %w[Ascending ASC]
        ]
        @property_criteria = [
            %w[Username username],
            ["E-mail Address", "email"]
        ]

        return(@users = User.order(created_at: :desc)) unless params.key? :commit

        if params[:type].present? && params[:type] == "query"
            property = params[:property] == "username" ? "username" : "email"
            safe_query = ActiveRecord::Base.connection.quote_string(params[:query])

            valid_sort = %w[created_at updated_at confirmed_at last_sign_in_at]
            valid_direction = %w[ASC DESC]

            sort = valid_sort.include?(params[:sort]) ? params[:sort] : "created_at"
            direction =
                valid_direction.include?(params[:order]) ? params[:order] : "ASC"

            query_order = Arel.sql("#{property} ILIKE '%#{safe_query}%' DESC")
            date_order = Arel.sql("#{sort} #{direction}")

            @users = User.order(query_order, date_order)
        else
            @users = User.order("#{params[:sort]} #{params[:order]}")
        end
    end

    def edit
        @user_target = User.find_by(username: params[:username])
        @current_sign_in_location = nil
        @last_sign_in_location = nil
        if @user_target.current_sign_in_ip
            res = HTTParty.get("https://ipwho.is/#{@user_target.current_sign_in_ip}")
            body = JSON.parse res.body
            @current_sign_in_location = "#{body["city"]}, #{body["region"]}, #{body["country"]}" if body["success"]
        end
        if @user_target.last_sign_in_ip
            res = HTTParty.get("https://ipwho.is/#{@user_target.last_sign_in_ip}")
            body = JSON.parse res.body
            @last_sign_in_location = "#{body["city"]}, #{body["region"]}, #{body["country"]}" if body["success"]
        end
        find_ban_data
    end

    def update
        @user_target = User.find_by(username: params[:username])
        find_ban_data

        was_verified = @user_target.verified?
        email_before = @user_target.email

        unless @user_target.update(edit_params)
            flash.now.alert = ["Failed to save user for the following reasons"].concat(
                @user_target.get_errors
            )
            return render :edit, status: :unprocessable_entity
        end

        @user_target.update(confirmed_at: Time.now) if edit_params[:confirmed] && !was_verified

        if edit_params[:email] != email_before || (!@user_target.verified? && was_verified)
            @user_target.update(confirmed: false, confirmed_at: nil)
            @user_target.send_verification_email
            flash.notice = "Saved user and verification E-mail was sent"
        else
            flash.notice = "Saved user"
        end
        redirect_to admin_user_edit_path(@user_target.username)
    end

    def ban_form
        @user_target = User.find_by(username: params[:username])
    end

    def ban
        User.find_by(username: params[:username]).update ban_params
        flash.notice = "User banned"
        redirect_to admin_user_edit_path
    end

    def unban
        User.find_by(username: params[:username]).update banned: false
        flash.notice = "User unbanned"
        redirect_to admin_user_edit_path
    end

    def ban_ip
        return redirect_to params[:return], notice: "IP is already banned" if BannedIp.find_by(ip: ban_ip_params[:ip]).present?

        BannedIp.create ban_ip_params
        redirect_to params[:return], notice: "IP #{ban_ip_params[:ip]} was banned"
    end

    def unban_ip
        return redirect_to params[:return], notice: "IP was not banned" unless BannedIp.find_by(ip: params[:ip]).present?

        BannedIp.find_by(ip: params[:ip]).destroy
        redirect_to params[:return], notice: "IP #{params[:ip]} was unbanned"
    end

    def destroy_token
        @user_target = User.find_by(username: params[:username])
        @token = @user_target.signed_id purpose: :destroy_user, expires_in: 1.day
    end

    def destroy
        user = User.find_signed params[:destroy_token], purpose: :destroy_user

        if user.present?
            user.destroy
            flash.notice = "User deleted"
        else
            flash.alert = "Could not delete user. Retry again later"
        end
        redirect_to admin_users_path
    end

    def send_verification
        user = User.find_by(username: params[:username])
        sent = user.send_verification_email
        notice = sent ? "Verification E-mail sent to user (#{user.email})" : "Verification E-mail wasn't sent because either the user is already verified or something went wrong"
        redirect_to admin_user_edit_path(user.username), notice:
    end

    def send_password_reset
        user = User.find_by(username: params[:username])
        user.send_reset_password_email
        redirect_to admin_user_edit_path(user.username), notice: "Password reset E-mail sent to user (#{user.email})"
    end

    def prepare_email
        @user_target = User.find_by(username: params[:username])
    end

    def send_email
        user = User.find_by(username: params[:username])
        UserMailer
            .with(email: user.email, subject: params[:subject], body: params[:body])
            .email_to_user
            .deliver_later
        redirect_to admin_user_edit_path(user.username), notice: "E-mail sent to user (#{user.email})"
    end

    private

    def edit_params
        params.require(:user).permit(
            :username,
            :email,
            :unconfirmed_email,
            :role,
            :confirmed
        )
    end

    def ban_params
        params.require(:user).permit(:banned, :ban_reason)
    end

    def ban_ip_params
        params.require(:banned_ip).permit(:ip, :reason)
    end

    def find_ban_data
        @referenced_ips_banned = [@user_target&.current_sign_in_ip, @user_target&.last_sign_in_ip]
        @referenced_ips_banned = @referenced_ips_banned.uniq.map { |ip| BannedIp.find_by(ip:) }.filter(&:present?)
        @ip_ban_reasons = @referenced_ips_banned.map(&:reason)
        @referenced_ips_banned.map!(&:ip)
    end
end

app/controllers/user/password_controller.rb
class User::PasswordController < ApplicationController
    before_action { setup_locale "user.password" }

    def reset
        redirect_to user_path, notice: t("user.sessions.new.already_logged_in") if logged_in?
    end

    def send_email
        override_action "reset"

        user = User.find_by_username_or_email(params[:username])

        unless user.present?
            flash.now.alert = tp("wrong_username")
            return render :reset, status: 401
        end

        user.send_reset_password_email
        redirect_to root_path, notice: tp("sent_email")
    end

    def edit
        user =
            User.find_signed params[:password_reset_token], purpose: :reset_password
        return if user.present?

        redirect_to root_path, alert: tp("invalid_link")
    end

    def update
        override_action "edit"

        user = User.find_signed params[:password_reset_token], purpose: :reset_password
        return redirect_to root_path, alert: tp("invalid_link") unless user.present?

        if user.update(
            password: params[:password],
            password_confirmation: params[:password_confirmation]
        )
            session[:user_id] = user.id

            user.sign_in request.remote_ip

            redirect_to user_path, notice: tp("changed_password")
        else
            flash.now.alert = user.get_errors
            render :edit, status: :unprocessable_entity
        end
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
    def display_field(field)
        field.present? ? field : "Not defined"
    end
end

app/helpers/api/user_helper.rb
module Api::UserHelper
end

app/helpers/user/password_helper.rb
module User::PasswordHelper
end

app/helpers/user/sessions_helper.rb
module User::SessionsHelper
end

app/helpers/user/user_helper.rb
module User::UserHelper
end

app/helpers/user/verification_helper.rb
module User::VerificationHelper
end

app/views/user/user/_data_field.html.erb
<div class="flex flex-col gap-1 dark:border-gray-700 border-b last:border-none">
    <div class="flex justify-between">
        <span><%= key %></span>
        <span><%= value %></span>
    </div>
</div>

app/views/user/user/edit.html.erb
<h1><%= tp "title" %></h1>

<%= form_with url: user_edit_path, model: @user, method: :patch, class: "flex flex-col items-center" do |form| %>
    <div class="text-field-container items-center">
        <%= form.label :username, tg("username") %>
        <%= form.text_field :username, autocomplete: "username", class: "text-field" %>
    </div>
    <div class="text-field-container items-center">
        <%= form.label :email, tg("emails"), class: "text-nowrap" %>
        <%= form.text_field :email, autocomplete: "email", class: "text-field" %>
    </div>
    <div class="text-field-container items-center">
        <%= form.label :password, tg("password"), class: "text-nowrap" %>
        <%= form.password_field :password, class: "text-field" %>
    </div>
    <div class="text-field-container items-center">
        <%= form.label :password_confirmation, tp("password_repeat"), class: "text-nowrap" %>
        <%= form.password_field :password_confirmation, class: "text-field" %>
    </div>
    <div class="text-field-container items-center">
        <%= form.label :password_challenge, tp("old_password"), class: "text-nowrap" %>
        <%= form.password_field :password_challenge, class: "text-field" %>
    </div>
    <div class="mt-2 max-w-96 w-full flex gap-2">
        <%= form.submit tg("save"), class: "btn-success-sleek grow" %>
        <%= link_to tp("cancel"), user_path, class: "btn-secondary-sleek grow" %>
    </div>
<% end %>

app/views/user/user/favorites.html.erb
<h1><%= tp "favorite_quizzes" %></h1>

<% if @quizzes.count.positive? %>
    <%= render partial: "partials/quiz_search", locals: { url: user_quizzes_path } %>
<% else %>
    <h4><%= tp "no_favorites" %></h4>
<% end %>
<%= render partial: "partials/quiz_list", locals: { quizzes: @quizzes } %>
<%= render partial: "partials/page_navigator", locals: { pages: @pages, params: @params } %>

app/views/user/user/library.html.erb
<h1><%= t ".library" %></h1>

<div class="mt-2 flex">
    <%= link_to t(".create_quiz"), quiz_create_path, class: "btn-primary w-full" %>
</div>

<%= render partial: "partials/quiz_list", locals: { quizzes: @quizzes, no_username: true } %>

<div class="mt-2 flex">
    <% if @user.quizzes.count > 10 %>
        <%= link_to t(".all_quizzes"), user_quizzes_path, class: "btn-primary w-full" %>
    <% end %>
</div>

app/views/user/user/new.html.erb
<h1><%= tp("create_account") %></h1>
<h4><%= tp("already_have_account") %> <%= link_to tp("login"), user_login_path %></h4>

<%= form_with url: user_create_path, model: @new_user, class: "flex flex-col items-center my-2" do |form| %>
    <div class="text-field-container">
        <%= form.text_field :username, autofocus: true, autocomplete: false, placeholder: tp("username"), class: "text-field" %>
    </div>
    <div class="text-field-container">
        <%= form.text_field :email, autocomplete: false, placeholder: tp("email"), class: "text-field" %>
    </div>
    <div class="text-field-container">
        <%= form.password_field :password, autocomplete: false, placeholder: tp("password"), class: "text-field" %>
    </div>
    <div class="text-field-container flex">
        <%= form.password_field :password_confirmation, autocomplete: false, placeholder: tp("repeat_password"), class: "text-field" %>
        <%= form.submit value: tp("submit_create_account"), class: "form-submit" %>
    </div>
    <div class="flex items-center justify-center gap-1 m-2">
        <%= form.check_box :agb, class: "border-teal-700 text-teal-700 focus:outline-none focus:ring-transparent rounded focus:ring-offset-0 dark:bg-gray-900" %>
        <%= form.label :agb, tp("accept_agb", link: link_to(tp("agb"), terms_of_service_path)).html_safe %>
    </div>
<% end %>

app/views/user/user/public.html.erb
<div class="flex justify-center items-center gap-2">
    <h1 class="p-0"><%= tp("profile", user: @target.username) %></h1>
    <%= image_tag @target.avatar_url, class: "h-16 w-16 rounded-full border-4 border-blue-600" %>
</div>

<div class="my-2 flex flex-col md:flex-row items-center md:justify-around gap-2 text-gray-600 dark:text-gray-500">
    <div><%= tp("created_ago", time_ago: distance_of_time_in_words_to_now(@target.created_at)) %></div>
    <div><%= tp("quizzes", quizzes: pluralize(@target.quizzes.count, tp("quiz"))) %></div>
    <div><%= tp("bugs_smashed", bugs: pluralize(@target.bugs_smashed, tp("bug"))) %></div>
</div>

<%= render partial: "partials/quiz_search", locals: { url: user_public_path } %>
<%= render partial: "partials/quiz_list", locals: { quizzes: @quizzes } %>
<br>
<%= render partial: "partials/page_navigator", locals: { params: @params, pages: @pages } %>

app/views/user/user/quizzes.html.erb
<h1><%= tp "my_quizzes" %></h1>

<% if @quizzes.count.positive? %>
    <%= render partial: "partials/quiz_search", locals: { url: user_quizzes_path } %>
<% else %>
    <h4><%= tp "no_quizzes" %></h4>
<% end %>
<%= render partial: "partials/quiz_list", locals: { quizzes: @quizzes } %>
<%= render partial: "partials/page_navigator", locals: { pages: @pages, params: @params } %>

app/views/user/user/request_destroy.html.erb
<div class="container text-center" data-controller="toast-button" data-target="#deleteToast">
    <h1><%= tp("delete_account") %></h1>
    <h3><%= tp("not_reversible") %></h3>
    <br>
    <%= form_with url: user_delete_path(@token), method: :delete do |form| %>
        <div class="flex flex-col gap-2">
            <div class="flex justify-center items-center gap-2">
                <%= form.check_box :destroy_quizzes, class: "rounded focus:ring-0 focus:ring-offset-0" %>
                <%= form.label :destroy_quizzes, t(".destroy_quizzes") %>
            </div>
            <div>
                <%= form.submit tp("delete"), class: "btn-danger-sleek", data: { turbo_confirm: tp("sure_to_delete") } %>
                <%= link_to tp("cancel"), user_path, class: "btn-secondary" %>
            </div>
        </div>
    <% end %>
</div>

app/views/user/user/settings.html.erb
<h1><%= tp("settings") %></h1>

<%= form_with url: user_settings_path, model: @user.setting do |form| %>
    <div class="flex justify-center">
        <div class="grow max-w-3xl divide-y dark:divide-gray-800">
            <div class="flex justify-between items-center py-2">
                <%= form.label :select, tp("language") %>
                <div class="flex items-center gap-2">
                    <%= image_tag "flags/#{@user.setting.locale}.jpg", class: "h-6 rounded" %>
                    <%= form.select :locale, Setting::LOCALES.map { |l| [tg("languages.#{l}"), l] }, {}, { class: "rounded border-none focus:ring-0 cursor-pointer hover:bg-gray-100 dark:bg-gray-900 dark:hover:bg-gray-800" } %>
                </div>
            </div>

            <div class="flex justify-between items-center py-2">
                <%= form.label :dark_mode, tg("settings.dark_mode") %>
                <%= form.check_box :dark_mode, class: "switch" %>
            </div>

            <div class="flex flex-col md:flex-row gap-2 items-center py-2">
                <span><%= tp "round_amount" %></span>
                <div class="flex gap-2 items-center grow w-full md:w-fit">
                    <!-- Required for tailwind to include the classes... -->
                    <span class="hidden peer/5 peer-checked/5:bg-blue-600 peer-checked/5:text-white"></span>
                    <span class="hidden peer/10 peer-checked/10:bg-blue-600 peer-checked/10:text-white"></span>
                    <span class="hidden peer/20 peer-checked/20:bg-blue-600 peer-checked/20:text-white"></span>
                    <span class="hidden peer/30 peer-checked/30:bg-blue-600 peer-checked/30:text-white"></span>
                    
                    <% Setting::ROUND_AMOUNTS.each do |amount| %>
                        <%= form.radio_button :round_amount, amount, class: "hidden peer/#{amount}" %>
                        <%= form.label :round_amount, amount, value: amount, class: "grow basis-0 text-center p-2 border-gray-300 dark:border-gray-700 border rounded cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors peer-checked/#{amount}:bg-blue-600 peer-checked/#{amount}:text-white" %>
                    <% end %>
                </div>
            </div>

            <% %i[cards_amount multi_amount write_amount].each do |key| %>
                <div class="flex justify-between items-center py-2">
                    <div>
                        <%= tg "settings.#{key}" %>
                    </div>
                    <%= form.number_field key, min: 1, max: 3, class: "dark:bg-gray-900 focus:ring-teal-700 focus:border-teal-700 dark:border-gray-700 border-gray-300 rounded" %>
                </div>
            <% end %>
        </div>
    </div>
    <div class="flex justify-center my-2">
        <%= form.submit value: tp("save"), class: "btn-success" %>
    </div>
<% end %>

app/views/user/user/show.html.erb
<h1><%= tp "title" %></h1>

<div class="grid grid-flow-row lg:grid-cols-2 lg:grid-flow-col gap-2">
    <div class="min-w-0 md:max-lg:px-36 p-2 bg-gray-100 dark:bg-gray-800 rounded">
        <h4><%= tp "column_names.data" %></h4>
        <strong><%= tp "data.title_1" %></strong>
        <div class="mb-1">
            <% @user_data.each do |key, value| %>
                <%= render partial: "data_field", locals: { key:, value: } %>
            <% end %>
        </div>
        <div class="flex">
            <% unless @user.confirmed? %>
                <%= link_to tp("buttons.confirm"), user_verification_send_path, class: "btn-primary-sleek grow mb-4" %>
            <% end %>
        </div>
        <strong><%= tp "data.title_2" %></strong>
        <div class="mb-4">
            <% @login_data.each do |key, value| %>
                <%= render partial: "data_field", locals: { key:, value: } %>
            <% end %>
        </div>
        <div class="flex gap-2">
            <%= link_to tp("buttons.edit"), user_edit_path, class: "btn-primary-sleek grow basis-0" %>
            <%= link_to tp("buttons.delete"), user_delete_path, class: "btn-danger-sleek grow basis-0" %>
        </div>
    </div>
    <div class="min-w-0 p-2 bg-gray-100 dark:bg-gray-800 rounded">
        <h4><%= tp "column_names.quizzes" %></h4>
        <% @user.quizzes.each do |quiz| %>
            <%= link_to quiz_show_path(quiz.uuid) do %>
                <div class="rounded truncate p-2 text-black hover:text-white hover:bg-blue-600 dark:text-white dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700 transition-colors">
                    <span><%= quiz.title %></span>
                </div>
            <% end %>
        <% end %>
    </div>
</div>