config/routes.rb
Rails.application.routes.draw do
    root "home#root"
    get "terms-of-service", to: "home#terms_of_service", as: "terms_of_service"
    get "privacy-policy", to: "home#privacy_policy", as: "privacy_policy"
    get "security-policy", to: "home#security_policy", as: "security_policy"
    get "sponsors", to: "home#sponsors", as: "sponsors"

    get "search", to: "home#search", as: "search"

    # User routes
    get "user/:username", to: "user/user#public", as: "user_public"

    scope :account do
        get "/", to: "user/user#show", as: "user"
        get "edit", to: "user/user#edit", as: "user_edit"
        patch "edit", to: "user/user#update"

        get "quizzes", to: "user/user#quizzes", as: "user_quizzes"
        get "favorites", to: "user/user#favorites", as: "user_favorites"
        get "library", to: "user/user#library", as: "user_library"

        get "settings", to: "user/user#settings", as: "user_settings"
        patch "settings", to: "user/user#update_settings"

        get "delete(/:destroy_token)",
            to: "user/user#request_destroy",
            as: "user_delete"
        delete "delete/:destroy_token", to: "user/user#destroy"
    end

    scope :password do
        get "reset", to: "user/password#reset", as: "user_password_reset"
        post "reset", to: "user/password#send_email"

        get "edit/:password_reset_token",
            to: "user/password#edit",
            as: "user_password_edit"
        post "edit/:password_reset_token", to: "user/password#update"
    end

    scope :verify do
        get "/", to: "user/verification#success", as: "user_verification_success"
        get "send", to: "user/verification#send_email", as: "user_verification_send"
        get "pending",
            to: "user/verification#pending",
            as: "user_verification_pending"
        get ":verification_token", to: "user/verification#verify", as: "user_verify"
    end

    patch "language", to: "user/user#change_lang", as: "change_language"

    get "signup", to: "user/user#new", as: "user_create"
    post "signup", to: "user/user#create"

    get "login", to: "user/sessions#new", as: "user_login"
    post "login", to: "user/sessions#create"

    get "logout", to: "user/sessions#destroy", as: "user_logout"

    # Quiz routes
    namespace :quiz do
        get "create", to: "quiz#new", as: "create"
        post "create", to: "quiz#create"

        scope ":quiz_uuid" do
            get "/", to: "quiz#show", as: "show"
            get "edit", to: "quiz#edit", as: "edit"
            patch "edit", to: "quiz#update"
            get "delete", to: "quiz#request_destroy", as: "request_destroy"
            delete "delete/:destroy_token", to: "quiz#destroy", as: "delete"

            patch "favorite", to: "quiz#favorite", as: "favorite"

            get "cards", to: "quiz#cards", as: "cards"
            get "write", to: "quiz#write", as: "write"
            get "multi", to: "quiz#multi", as: "multi"
            get "smart", to: "quiz#smart", as: "smart"

            get "report", to: "quiz#new_report", as: "report"
            post "report", to: "quiz#report"
        end
    end

    # Bug report routes
    post "report", to: "admin/bug_report#create", as: "bug_report"

    # API routes
    namespace :api do
        defaults format: :json do
            scope :user do
                get "username/validate/:username", to: "user#username_validator", as: "username_validator"
                put "create", to: "user#create", as: "user_create"
                post "login", to: "user#login", as: "user_login"
                post "refresh", to: "user#refresh_token", as: "user_refresh_token"

                get "search(/:page)", to: "user#search", as: "user_search"

                get "quizzes(/:page)", to: "user#quizzes", as: "user_quizzes"
                get "favorites(/:page)", to: "user#favorites", as: "user_favorites"
                get ":username/public(/:page)", to: "user#public", as: "user_public"

                get "delete_token", to: "user#request_delete_token", as: "user_request_delete"
                delete "delete/:destroy_token", to: "user#destroy", as: "user_destroy"

                patch "update", to: "user#update", as: "user_update"
                patch "settings", to: "user#update_settings", as: "user_update_settings"

                get "data", to: "user#data", as: "user_data"
            end

            scope :quiz do
                put "create", to: "quiz#create", as: "quiz_create"

                get "search(/:page)", to: "quiz#search", as: "quiz_search"

                scope ":quiz_id" do
                    get "data", to: "quiz#data", as: "quiz_data"

                    post "report", to: "quiz#report", as: "quiz_report"

                    patch "update", to: "quiz#update", as: "quiz_update"
                    patch "favorite", to: "quiz#favorite_quiz", as: "quiz_favorite"

                    scope :score do
                        patch "sync", to: "quiz#sync_score", as: "quiz_sync_score"
                        patch "reset/:mode", to: "quiz#reset_score", as: "quiz_reset_score"
                        patch ":score_id/favorite", to: "quiz#favorite", as: "quiz_favorite_score"
                        patch ":score_id/:mode", to: "quiz#score", as: "quiz_score"
                    end

                    get "delete_token", to: "quiz#request_destroy", as: "quiz_request_delete"
                    delete "delete/:destroy_token", to: "quiz#destroy", as: "quiz_delete"
                end
            end

            get "languages", to: "api#languages"

            put "bug/create", to: "bug_report#create"
        end

        scope :docs do
            get "/", to: "docs#index", as: "docs"
            get "users", to: "docs#users", as: "docs_users"
            get "quizzes", to: "docs#quizzes", as: "docs_quizzes"
            get "authentication", to: "docs#authentication", as: "docs_authentication"
            get "errors", to: "docs#general_errors", as: "docs_general_errors"
            get "bugs", to: "docs#bugs", as: "docs_bugs"
            get "languages", to: "docs#languages", as: "docs_languages"
        end
    end

    # Admin routes
    namespace :admin do
        get "users", to: "users#index", as: "users"

        get "ban_ip", to: "users#ban_ip_form", as: "ban_ip"
        put "ban_ip", to: "users#ban_ip"
        delete "ban_ip", to: "users#unban_ip"

        scope :bugs do
            scope :triage do
                get "/", to: "bug_report#triage", as: "bug_triage"
                get ":bug_report_id", to: "bug_report#triage_show", as: "bug_triage_show"
                patch ":bug_report_id", to: "bug_report#triage_verdict"
            end

            get "list", to: "bug_report#list", as: "bugs"

            scope ":bug_id" do
                get "/", to: "bug_report#show", as: "bug"
                patch "status", to: "bug_report#status", as: "bug_status"
            end
        end

        scope :transactions do
            get "/", to: "transaction#list", as: "transactions"
            get "removed", to: "transaction#removed", as: "removed_transactions"

            get "create", to: "transaction#new", as: "new_transaction"
            post "create", to: "transaction#create"

            scope ":transaction_id" do
                get "/", to: "transaction#show", as: "show_transaction"

                delete "delete", to: "transaction#delete", as: "delete_transaction"
                patch "restore", to: "transaction#restore", as: "restore_transaction"
            end
        end

        scope :user do
            scope ":username" do
                get "delete(/:destroy_token)",
                    to: "users#destroy_token",
                    as: "user_delete"
                delete "delete/:destroy_token", to: "users#destroy"

                get "ban", to: "users#ban_form", as: "user_ban"
                patch "ban", to: "users#ban"
                patch "unban", to: "users#unban", as: "user_unban"
            end

            scope "edit/:username" do
                get "/", to: "users#edit", as: "user_edit"
                patch "/", to: "users#update"
            end

            scope ":username/send" do
                get "verification",
                    to: "users#send_verification",
                    as: "user_send_verification"
                get "reset",
                    to: "users#send_password_reset",
                    as: "user_send_password_reset"
                get "email", to: "users#prepare_email", as: "user_send_email"
                post "email", to: "users#send_email"
            end
        end

        get "quiz/report/:quiz_report_id", to: "quiz#show_report", as: "quiz_report"
        get "quiz/triage", to: "quiz#triage", as: "quiz_report_triage"
        post "quiz/triage/:triage_id/ignore", to: "quiz#ignore_triage", as: "quiz_report_ignore_triage"
        scope "quiz/:quiz_id" do
            get "edit", to: "quiz#edit", as: "quiz_edit"
            post "edit", to: "quiz#update", as: "quiz_update"
            get "delete", to: "quiz#request_destroy", as: "quiz_request_delete"
            delete "delete/:delete_token", to: "quiz#destroy", as: "quiz_delete"
        end
    end
end

app/controllers/admin/quiz_controller.rb
class Admin::QuizController < ApplicationController
    around_action :locale_en
    before_action :require_admin!

    def edit
        @quiz = Quiz.find_by(uuid: params[:quiz_id])
        @update_url = params[:triage].present? ? admin_quiz_update_path(triage: params[:triage]) : admin_quiz_update_path
        @cancel_path = params[:triage].present? ? admin_quiz_report_triage_path : quiz_show_path(@quiz.uuid)
    end

    def update
        @quiz = Quiz.find_by(uuid: params[:quiz_id])

        redirect_to root_path, notice: "Quiz was not found" unless @quiz.present?

        if @quiz.update(quiz_params)
            if params[:triage].present?
                QuizReport.find(params[:triage]).update status: :solved
                redirect_to admin_quiz_report_triage_path, notice: "Triage solved though edit"
            else
                redirect_to quiz_show_path(@quiz.uuid), notice: "Quiz updated as admin"
            end
        else
            flash.now.alert = @quiz.get_errors
            render :edit, status: :unprocessable_entity
        end
    end

    def request_destroy
        @quiz = Quiz.find_by(uuid: params[:quiz_id])
        @destroy_token = @quiz.signed_id purpose: :admin_destroy, expires_in: 1.hour
        @destroy_path = params[:triage].present? ? admin_quiz_delete_path(delete_token: @destroy_token, triage: params[:triage]) : admin_quiz_delete_path(delete_token: @destroy_token)
        @cancel_path = params[:triage].present? ? admin_quiz_report_triage_path : quiz_show_path(@quiz.uuid)
    end

    def destroy
        quiz = Quiz.find_signed(params[:delete_token], purpose: :admin_destroy)

        if quiz.present?
            quiz.destroy
            if params[:triage].present?
                QuizReport.find(params[:triage]).update status: :deleted
                redirect_to admin_quiz_report_triage_path, notice: "Triage solved by deleting Quiz"
            else
                redirect_to root_path, notice: "Quiz was destroyed"
            end
        elsif params[:triage].present?
            redirect_to admin_quiz_report_triage_path, alert: "Could not destroy Quiz. Token might have expired"
        else
            redirect_to quiz_show_path(params[:quiz_id]), alert: "Could not destroy Quiz. Token might have expired"
        end
    end

    def show_report
        @report = QuizReport.find(params[:quiz_report_id])
        @reported_quiz = @report.quiz
        reports = QuizReport::KEYS.filter { |k| @report[k] }
        @reported_for = reports.map { |s| s.to_s.gsub("_", " ").capitalize }.join(", ")

        render :triage if @report.status == "open"
    end

    def triage
        @report = QuizReport.order(created_at: :asc).where(status: :open).first

        return unless @report.present?

        @reported_quiz = @report.quiz
        reports = QuizReport::KEYS.filter { |k| @report[k] }
        @reported_for = reports.map { |s| s.to_s.gsub("_", " ").capitalize }.join(", ")
    end

    def ignore_triage
        QuizReport.find(params[:triage_id]).update status: :ignored
        redirect_to admin_quiz_report_triage_path, notice: "Quiz report ignored"
    end

    private

    def quiz_params
        params.require(:quiz).permit(
            :title,
            :description,
            :from,
            :to,
            :visibility,
            translations_attributes: %i[id word translation _destroy]
        )
    end
end

app/controllers/quiz/quiz_controller.rb
class Quiz::QuizController < ApplicationController
    include ApiUtils

    before_action :require_login! do
        setup_locale "quiz.quiz"
    end

    before_action only: %i[show cards smart write multi] do
        override_action :show

        @access_token = generate_access_token(current_user, 31.days)

        @quiz = Quiz.find_by(uuid: params[:quiz_uuid])
        redirect_to root_path, notice: tp("not_found") unless @quiz.present? && @quiz.user_allowed_to_view?(current_user)
        redirect_to root_path, notice: tp("no_translations") unless @quiz.translations_count.positive?
    end

    def cards; end

    def smart; end

    def write; end

    def multi; end

    def favorite
        @quiz = Quiz.find_by(uuid: params[:quiz_uuid])
        return unless @quiz.present?

        if (favorite = @user.favorite_quizzes.find_by(quiz_id: @quiz.id)).present?
            favorite.destroy
        else
            @user.favorite_quizzes.create quiz_id: @quiz.id
        end

        redirect_to quiz_show_path
    end

    def new
        @quiz = @user.quizzes.new
        4.times { @quiz.translations.build }
    end

    def create
        override_action :new

        @quiz = @user.quizzes.new(quiz_params)
        if @quiz.save
            redirect_to quiz_show_path(@quiz.uuid), notice: tp("quiz_created")
        else
            flash.now.alert = @quiz.get_errors
            4.times { @quiz.translations.build } if @quiz.translations.count.zero?
            render :new, status: :unprocessable_entity
        end
    end

    def show
        @quiz = Quiz.find_by(uuid: params[:quiz_uuid])

        return redirect_to root_path, notice: tp("not_found") unless @quiz.present?

        redirect_to root_path, alert: t("errors.not_allowed_to_view_quiz") unless @quiz.user_allowed_to_view? @user

        @learn_data = @quiz.learn_data(@user).sort_by { |t| t[:id] }
    end

    def request_destroy
        @quiz = @user.quizzes.find_by(uuid: params[:quiz_uuid])

        if @quiz.present?
            @token = @quiz.signed_id purpose: :destroy_quiz, expires_in: 1.day
        else
            redirect_to root_path
        end
    end

    def edit
        override_action "new"

        @quiz = @user.quizzes.find_by(uuid: params[:quiz_uuid])

        return redirect_to root_path, notice: tp("not_found") unless @quiz.present?

        4.times { @quiz.translations.build } unless @quiz.translations.count.positive?
    end

    def update
        override_action "new"

        @quiz = @user.quizzes.find_by(uuid: params[:quiz_uuid])

        redirect_to root_path, notice: tp("not_found") unless @quiz.present?

        if @quiz.update(quiz_params)
            redirect_to quiz_show_path(@quiz.uuid), notice: tp("saved")
        else
            flash.now.alert = @quiz.get_errors
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        quiz = Quiz.find_signed params[:destroy_token], purpose: :destroy_quiz

        return redirect_to root_path, notice: tp("not_found") unless quiz.present?

        if quiz.user == @user
            quiz.destroy
            flash.notice = tp("deleted")
        else
            flash.alert = tp("not_allowed")
        end
        redirect_to root_path
    end

    def new_report
        @quiz = Quiz.find_by uuid: params[:quiz_uuid]
        @quiz_report = QuizReport.new
    end

    def report
        @quiz = Quiz.find_by uuid: params[:quiz_uuid]
        @quiz_report = @quiz.quiz_reports.new(quiz_report_params)

        @quiz_report.user = @user if logged_in?

        if @quiz_report.save
            AdminMailer.with(quiz: @quiz, quiz_report: @quiz_report).new_quiz_report.deliver_later
            redirect_to quiz_show_path(@quiz_report.quiz.uuid), notice: t("quiz.quiz.report.saved")
        else
            flash.now.alert = t("quiz.quiz.report.failed")
            render :new_report, status: :unprocessable_entity
        end
    end

    private

    def quiz_params
        params.require(:quiz).permit(
            :title,
            :description,
            :from,
            :to,
            :visibility,
            translations_attributes: %i[id word translation _destroy]
        )
    end

    def quiz_report_params
        params.require(:quiz_report).permit(
            :description,
            :sexual,
            :violence,
            :hate,
            :spam,
            :child_abuse,
            :mobbing
        )
    end
end

app/helpers/admin/quiz_helper.rb
module Admin::QuizHelper
end

app/helpers/api/quiz_helper.rb
module Api::QuizHelper
end

app/helpers/quiz/quiz_helper.rb
module Quiz::QuizHelper
end

app/views/quiz/quiz/_quiz_form.html.erb
<h1><%= title %></h1>

<%= form_with model: @quiz, method:, url: do |form| %>
    <div class="flex justify-center">
        <div class="grow max-w-5xl space-y-2">
            <div class="flex md:flex-row flex-col gap-2">
                <div class="md:grow flex sm:flex-row flex-col rounded border border-gray-300 dark:border-gray-700">
                    <%= form.label :title, t("quiz.quiz.new.title"), class: "py-2 px-5 text-center sm:text-start text-xl bg-gray-100 dark:bg-gray-800" %>
                    <%= form.text_field :title, placeholder: tp("title_placeholder"), data: { test_id: "quiz-title" }, class: "text-field sm:m-px rounded rounded-t-none sm:rounded-e sm:rounded-s-none focus:ring-2 focus:ring-teal-600" %>
                </div>
                <%= form.select :visibility, Quiz::VISIBILITIES.map { |v| [tg("visibilities.#{v}"), v] }, {}, { class: "rounded border-gray-300 focus:ring-1 focus:ring-teal-600 focus:border-teal-600 dark:border-gray-700 dark:bg-gray-900 cursor-pointer" } %>
            </div>
            <div class="flex sm:flex-row flex-col rounded border border-gray-300 dark:border-gray-700">
                <div class="flex items-center justify-center py-2 px-5 bg-gray-100 dark:bg-gray-800">
                    <span class="text-xl"><%= t "quiz.quiz.new.description" %></span>
                </div>
                <%= form.text_area :description, placeholder: t("quiz.quiz.new.description_placeholder"), data: { test_id: "quiz-description" }, class: "text-field sm:m-px rounded rounded-t-none sm:rounded-e sm:rounded-s-none focus:ring-2 focus:ring-teal-600 min-h-10" %>
            </div>
            <div class="flex md:flex-row flex-col gap-2">
                <%= render partial: "quiz/quiz/translation_lang", locals: { form: form, field: :from, name: t("quiz.quiz.new.lang_1") } %>
                <%= render partial: "quiz/quiz/translation_lang", locals: { form: form, field: :to, name: t("quiz.quiz.new.lang_2") } %>
            </div>
            <div data-controller="create-quiz" class="space-y-2">
                <div class="flex gap-2">
                    <label for="quiz-import-file" class="btn-primary-sleek grow basis-0"><%= t("quiz.quiz.new.import") %>
                    </label>
                    <button type="button" class="btn-primary-sleek grow basis-0" data-action="create-quiz#show_import_text"><%= t "quiz.quiz.new.import_text" %></button>
                    <input type="file" id="quiz-import-file" data-action="click->create-quiz#import_quiz_click change->create-quiz#import_quiz" data-confirm-message="<%= t "quiz.quiz.new.import_confirm" %>" data-error-message="<%= t "quiz.quiz.new.import_error" %>" data-create-quiz-target="importQuiz" class="hidden rounded border border-gray-300 dark:border-gray-700 p-2 justify-between align-center gap-2 md:h-12" class="hidden"/>
                </div>
                <div class="hidden" data-create-quiz-target="importText">
                    <textarea class="w-full dark:bg-transparent focus:border-teal-700 rounded focus:ring-1 -ring-offset-2 focus:ring-teal-600 min-h-10 border border-gray-300 dark:border-gray-600" placeholder="<%= t "quiz.quiz.new.paste_text" %>" data-create-quiz-target="importTextField"></textarea>
                    <button type="button" class="btn-success-sleek w-full" data-action="create-quiz#import_text"><%= t "quiz.quiz.new.load" %></button>
                </div>
                <div data-create-quiz-target="translations" class="space-y-2">
                    <%= form.fields_for :translations, @quiz.translations.sort_by(&:created_at) do |translation_form| %>
                        <%= render partial: "quiz/quiz/translation_form", locals: { translation_form: } %>
                    <% end %>
                </div>
                <button data-action="create-quiz#add_translation" class="btn-primary-sleek w-full"><%= t "quiz.quiz.new.add_translation" %></button>
            </div>
            <div class="flex justify-around gap-2">
                <%= form.submit commit, class: "btn-success text-xl", data: { test_id: "quiz-create" } %>
                <%= link_to t("quiz.quiz.new.cancel"), cancel_path, class: "btn-primary text-xl" %>
            </div>
        </div>
    </div>
<% end %>

app/views/quiz/quiz/_translation_lang.html.erb
<div class="grow basis-0 flex sm:flex-row flex-col rounded border border-gray-300 dark:border-gray-700">
    <span class="text-xl p-2 bg-gray-100 dark:bg-gray-800"><%= name %></span>
    <%= form.select field, Language.all.map { |l| [tg("languages.#{l.locale}"), l.id] }, {}, { data: { test_id: "#{field.to_s}-lang" }, class: "grow rounded-b sm:rounded-s-none sm:rounded-e border-none focus:ring-2 focus:ring-teal-600 focus:border-teal-600 dark:bg-gray-900 cursor-pointer" } %>
</div>

app/views/quiz/quiz/edit.html.erb
<%= render partial: "quiz_form", locals: {
    title: tp("title_edit"),
    method: :patch,
    commit: tp("save"),
    url: quiz_edit_path(@quiz.uuid),
    cancel_path: quiz_show_path(@quiz.uuid)
} %>

app/views/quiz/quiz/new.html.erb
<%= render partial: "quiz_form", locals: {
    title: tp("create_quiz"),
    method: :post,
    commit: tp("create"),
    url: quiz_create_path,
    cancel_path: user_path
} %>

app/views/quiz/quiz/new_report.html.erb
<h1 class="mb-5"><%= t ".title", title: @quiz.title %></h1>

<%= form_with model: @quiz_report, url: quiz_report_path do |form| %>
    <p class="flex justify-center">
        <%= form.text_area :description, placeholder: t(".description_placeholder"), class: "text-field  sm:m-px rounded ring-2 ring-gray-300 dark:ring-gray-700 focus:ring-2 focus:ring-teal-600 min-h-10 max-w-xl" %>
    </p>
    
    <div class="flex justify-center mt-5">
        <div>
            <p>
                <h3 class="text-start"><%= t ".quiz_is" %></h3>
                <ul>
                    <% QuizReport::KEYS.each do |key| %>
                        <li class="mt-2 flex flex-row align-center gap-2">
                            <%= form.check_box key, class: "border-gray-300 dark:border-gray-700 focus:border-teal-700 text-teal-700 focus:outline-none focus:ring-transparent rounded focus:ring-offset-0 dark:bg-gray-900  h-6 w-6" %>
                            <%= form.label key, t(".#{key.to_s}") %>
                        </li>
                    <% end %>
                </ul>
            </p>

            <p class="mt-5 w-full">
                <%= form.submit t(".report"), class: "form-submit ms-0 w-full h-10 text-xl" %>
            </p>
        </div>
    </div>
<% end %>

app/views/quiz/quiz/request_destroy.html.erb
<h1><%= tp "really_delete", quiz: @quiz.title %></h1>

<div class="flex justify-center gap-2">
    <%= button_to tp("delete"), quiz_delete_path(@quiz.uuid, @token), method: :delete, class: "btn-danger", data: { turbo_confirm: tp("sure_to_delete") } %>
    <%= link_to tp("cancel"), quiz_show_path(@quiz.uuid), class: "btn-primary" %>
</div>

app/views/quiz/quiz/show.html.erb
<div class="mb-2 md:mb-0 flex flex-col md:flex-row justify-center items-center md:gap-2">
    <h1 class="text-3xl md:text-4xl"><%= @quiz.title %></h1>
    <% if logged_in? %>
        <%= link_to quiz_favorite_path, data: { turbo_method: :patch } do %>
            <%= render partial: "svgs/star", locals: { height: "35px", filled: @user.favorite_quizzes.find_by(quiz_id: @quiz.id).present? } %>
        <% end %>
    <% end %>
</div>

<% if @user.admin? %>
    <h3 class="text-gray-600 dark:text-gray-500">
        <%= link_to t(".admin_edit"), admin_quiz_edit_path(@quiz.uuid) %>,
        <%= link_to t(".admin_delete"), admin_quiz_request_delete_path(@quiz.uuid) %>
    </h3>
<% end %>

<h3 class="text-gray-600 dark:text-gray-500">
    <%= link_to t(".report"), quiz_report_path(@quiz.uuid) %>
</h3>

<% unless @user == @quiz.user || @quiz.user.nil? %>
    <h3 class="text-gray-600 dark:text-gray-500"><%= tp("created_by", user: link_to(@quiz.user.username, user_public_path(@quiz.user.username))).html_safe %></h3>
<% end %>

<% if @quiz.description.present? %>
    <div data-controller="show-more">
        <h4 data-show-more-target="target" class="line-clamp-3"><%= @quiz.description %></h4>
        <h4
            data-show-more-target="showMore"
            data-action="click->show-more#show_more"
            class="hidden underline cursor-pointer"
        ><%= tg "show_more" %></h4>
        <h4
            data-show-more-target="showLess"
            data-action="click->show-more#show_less"
            class="hidden underline cursor-pointer"
        ><%= tg "show_less" %></h4>
    </div>
<% end %>

<div class="flex md:flex-row flex-col gap-2">
    <%= link_to tp("cards"), quiz_cards_path, class: "btn-primary grow basis-0" %>
    <%= link_to tp("write"), quiz_write_path, class: "btn-primary grow basis-0" %>
    <%= link_to tp("multiple_choice"), quiz_multi_path, class: "btn-primary grow basis-0" %>
    <%= link_to tp("smart"), quiz_smart_path, class: "btn-primary grow basis-0" %>
    <% if @quiz.user == @user %>
        <%= link_to tp("edit"), quiz_edit_path, class: "btn-primary grow basis-0" %>
        <%= link_to tp("delete"), quiz_request_destroy_path, class: "btn-danger grow basis-0" %>
    <% end %>
</div>

<div class="rounded mt-2 border divide-gray-300 divide-y border-gray-300 dark:border-gray-700 dark:divide-gray-700">
    <% @learn_data.each do |translation| %>
        <div class="flex divide-x divide-gray-300 dark:divide-gray-700">
            <div class="w-1/2 p-2 overflow-clip" title="<%= translation[:word] %>"><%= translation[:word] %></div>
            <div class="w-1/2 overflow-clip">
                <div class="flex divide-gray-300 dark:divide-gray-700 divide-x">
                    <div class="p-2 grow" title="<%= translation[:translation] %>"><%= translation[:translation] %></div>
                    <div 
                        data-controller="translation-favorite"
                        data-action="click->translation-favorite#toggle"
                        data-favorite="<%= translation[:favorite] %>"
                        data-score-id="<%= translation[:score_id] %>"
                        data-quiz-id="<%= @quiz.uuid %>"
                        data-access-token="<%= @access_token %>"
                        data-error="<%= tp("score_favorite_error") %>"
                        class="px-2 flex items-center cursor-pointer"
                    >
                        <div
                            data-translation-favorite-target="star"
                            class="<%= "hidden" unless translation[:favorite] %>"
                        >
                            <%= render partial: "svgs/star", locals: { height: "25px", filled: true } %>
                        </div>
                        <div
                            data-translation-favorite-target="star"
                            class="<%= "hidden" if translation[:favorite] %>"
                        >
                            <%= render partial: "svgs/star", locals: { height: "25px", filled: false } %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>