config/routes.rb
Rails.application.routes.draw do
    root "home#root"
    get "terms-of-service", to: "home#terms_of_service", as: "terms_of_service"
    get "privacy-policy", to: "home#privacy_policy", as: "privacy_policy"
    get "security-policy", to: "home#security_policy", as: "security_policy"
    get "sponsors", to: "home#sponsors", as: "sponsors"

    get "search", to: "home#search", as: "search"

    # User routes
    get "user/:username", to: "user/user#public", as: "user_public"

    scope :account do
        get "/", to: "user/user#show", as: "user"
        get "edit", to: "user/user#edit", as: "user_edit"
        patch "edit", to: "user/user#update"

        get "quizzes", to: "user/user#quizzes", as: "user_quizzes"
        get "favorites", to: "user/user#favorites", as: "user_favorites"
        get "library", to: "user/user#library", as: "user_library"

        get "settings", to: "user/user#settings", as: "user_settings"
        patch "settings", to: "user/user#update_settings"

        get "delete(/:destroy_token)",
            to: "user/user#request_destroy",
            as: "user_delete"
        delete "delete/:destroy_token", to: "user/user#destroy"
    end

    scope :password do
        get "reset", to: "user/password#reset", as: "user_password_reset"
        post "reset", to: "user/password#send_email"

        get "edit/:password_reset_token",
            to: "user/password#edit",
            as: "user_password_edit"
        post "edit/:password_reset_token", to: "user/password#update"
    end

    scope :verify do
        get "/", to: "user/verification#success", as: "user_verification_success"
        get "send", to: "user/verification#send_email", as: "user_verification_send"
        get "pending",
            to: "user/verification#pending",
            as: "user_verification_pending"
        get ":verification_token", to: "user/verification#verify", as: "user_verify"
    end

    patch "language", to: "user/user#change_lang", as: "change_language"

    get "signup", to: "user/user#new", as: "user_create"
    post "signup", to: "user/user#create"

    get "login", to: "user/sessions#new", as: "user_login"
    post "login", to: "user/sessions#create"

    get "logout", to: "user/sessions#destroy", as: "user_logout"

    # Quiz routes
    namespace :quiz do
        get "create", to: "quiz#new", as: "create"
        post "create", to: "quiz#create"

        scope ":quiz_uuid" do
            get "/", to: "quiz#show", as: "show"
            get "edit", to: "quiz#edit", as: "edit"
            patch "edit", to: "quiz#update"
            get "delete", to: "quiz#request_destroy", as: "request_destroy"
            delete "delete/:destroy_token", to: "quiz#destroy", as: "delete"

            patch "favorite", to: "quiz#favorite", as: "favorite"

            get "cards", to: "quiz#cards", as: "cards"
            get "write", to: "quiz#write", as: "write"
            get "multi", to: "quiz#multi", as: "multi"
            get "smart", to: "quiz#smart", as: "smart"

            get "report", to: "quiz#new_report", as: "report"
            post "report", to: "quiz#report"
        end
    end

    # Bug report routes
    post "report", to: "admin/bug_report#create", as: "bug_report"

    # API routes
    namespace :api do
        defaults format: :json do
            scope :user do
                get "username/validate/:username", to: "user#username_validator", as: "username_validator"
                put "create", to: "user#create", as: "user_create"
                post "login", to: "user#login", as: "user_login"
                post "refresh", to: "user#refresh_token", as: "user_refresh_token"

                get "search(/:page)", to: "user#search", as: "user_search"

                get "quizzes(/:page)", to: "user#quizzes", as: "user_quizzes"
                get "favorites(/:page)", to: "user#favorites", as: "user_favorites"
                get ":username/public(/:page)", to: "user#public", as: "user_public"

                get "delete_token", to: "user#request_delete_token", as: "user_request_delete"
                delete "delete/:destroy_token", to: "user#destroy", as: "user_destroy"

                patch "update", to: "user#update", as: "user_update"
                patch "settings", to: "user#update_settings", as: "user_update_settings"

                get "data", to: "user#data", as: "user_data"
            end

            scope :quiz do
                put "create", to: "quiz#create", as: "quiz_create"

                get "search(/:page)", to: "quiz#search", as: "quiz_search"

                scope ":quiz_id" do
                    get "data", to: "quiz#data", as: "quiz_data"

                    post "report", to: "quiz#report", as: "quiz_report"

                    patch "update", to: "quiz#update", as: "quiz_update"
                    patch "favorite", to: "quiz#favorite_quiz", as: "quiz_favorite"

                    scope :score do
                        patch "sync", to: "quiz#sync_score", as: "quiz_sync_score"
                        patch "reset/:mode", to: "quiz#reset_score", as: "quiz_reset_score"
                        patch ":score_id/favorite", to: "quiz#favorite", as: "quiz_favorite_score"
                        patch ":score_id/:mode", to: "quiz#score", as: "quiz_score"
                    end

                    get "delete_token", to: "quiz#request_destroy", as: "quiz_request_delete"
                    delete "delete/:destroy_token", to: "quiz#destroy", as: "quiz_delete"
                end
            end

            get "languages", to: "api#languages"

            put "bug/create", to: "bug_report#create"
        end

        scope :docs do
            get "/", to: "docs#index", as: "docs"
            get "users", to: "docs#users", as: "docs_users"
            get "quizzes", to: "docs#quizzes", as: "docs_quizzes"
            get "authentication", to: "docs#authentication", as: "docs_authentication"
            get "errors", to: "docs#general_errors", as: "docs_general_errors"
            get "bugs", to: "docs#bugs", as: "docs_bugs"
            get "languages", to: "docs#languages", as: "docs_languages"
        end
    end

    # Admin routes
    namespace :admin do
        get "users", to: "users#index", as: "users"

        get "ban_ip", to: "users#ban_ip_form", as: "ban_ip"
        put "ban_ip", to: "users#ban_ip"
        delete "ban_ip", to: "users#unban_ip"

        scope :bugs do
            scope :triage do
                get "/", to: "bug_report#triage", as: "bug_triage"
                get ":bug_report_id", to: "bug_report#triage_show", as: "bug_triage_show"
                patch ":bug_report_id", to: "bug_report#triage_verdict"
            end

            get "list", to: "bug_report#list", as: "bugs"

            scope ":bug_id" do
                get "/", to: "bug_report#show", as: "bug"
                patch "status", to: "bug_report#status", as: "bug_status"
            end
        end

        scope :transactions do
            get "/", to: "transaction#list", as: "transactions"
            get "removed", to: "transaction#removed", as: "removed_transactions"

            get "create", to: "transaction#new", as: "new_transaction"
            post "create", to: "transaction#create"

            scope ":transaction_id" do
                get "/", to: "transaction#show", as: "show_transaction"

                delete "delete", to: "transaction#delete", as: "delete_transaction"
                patch "restore", to: "transaction#restore", as: "restore_transaction"
            end
        end

        scope :user do
            scope ":username" do
                get "delete(/:destroy_token)",
                    to: "users#destroy_token",
                    as: "user_delete"
                delete "delete/:destroy_token", to: "users#destroy"

                get "ban", to: "users#ban_form", as: "user_ban"
                patch "ban", to: "users#ban"
                patch "unban", to: "users#unban", as: "user_unban"
            end

            scope "edit/:username" do
                get "/", to: "users#edit", as: "user_edit"
                patch "/", to: "users#update"
            end

            scope ":username/send" do
                get "verification",
                    to: "users#send_verification",
                    as: "user_send_verification"
                get "reset",
                    to: "users#send_password_reset",
                    as: "user_send_password_reset"
                get "email", to: "users#prepare_email", as: "user_send_email"
                post "email", to: "users#send_email"
            end
        end

        get "quiz/report/:quiz_report_id", to: "quiz#show_report", as: "quiz_report"
        get "quiz/triage", to: "quiz#triage", as: "quiz_report_triage"
        post "quiz/triage/:triage_id/ignore", to: "quiz#ignore_triage", as: "quiz_report_ignore_triage"
        scope "quiz/:quiz_id" do
            get "edit", to: "quiz#edit", as: "quiz_edit"
            post "edit", to: "quiz#update", as: "quiz_update"
            get "delete", to: "quiz#request_destroy", as: "quiz_request_delete"
            delete "delete/:delete_token", to: "quiz#destroy", as: "quiz_delete"
        end
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :require_admin!

    def index
        @sort_criteria = [
            ["Date created", "created_at"],
            ["Date updated", "updated_at"],
            ["Date confirmed", "confirmed_at"],
            ["Last login", "last_sign_in_at"]
        ]
        @order_criteria = [
            %w[Descending DESC],
            %w[Ascending ASC]
        ]
        @property_criteria = [
            %w[Username username],
            ["E-mail Address", "email"]
        ]

        return(@users = User.order(created_at: :desc)) unless params.key? :commit

        if params[:type].present? && params[:type] == "query"
            property = params[:property] == "username" ? "username" : "email"
            safe_query = ActiveRecord::Base.connection.quote_string(params[:query])

            valid_sort = %w[created_at updated_at confirmed_at last_sign_in_at]
            valid_direction = %w[ASC DESC]

            sort = valid_sort.include?(params[:sort]) ? params[:sort] : "created_at"
            direction =
                valid_direction.include?(params[:order]) ? params[:order] : "ASC"

            query_order = Arel.sql("#{property} ILIKE '%#{safe_query}%' DESC")
            date_order = Arel.sql("#{sort} #{direction}")

            @users = User.order(query_order, date_order)
        else
            @users = User.order("#{params[:sort]} #{params[:order]}")
        end
    end

    def edit
        @user_target = User.find_by(username: params[:username])
        @current_sign_in_location = nil
        @last_sign_in_location = nil
        if @user_target.current_sign_in_ip
            res = HTTParty.get("https://ipwho.is/#{@user_target.current_sign_in_ip}")
            body = JSON.parse res.body
            @current_sign_in_location = "#{body["city"]}, #{body["region"]}, #{body["country"]}" if body["success"]
        end
        if @user_target.last_sign_in_ip
            res = HTTParty.get("https://ipwho.is/#{@user_target.last_sign_in_ip}")
            body = JSON.parse res.body
            @last_sign_in_location = "#{body["city"]}, #{body["region"]}, #{body["country"]}" if body["success"]
        end
        find_ban_data
    end

    def update
        @user_target = User.find_by(username: params[:username])
        find_ban_data

        was_verified = @user_target.verified?
        email_before = @user_target.email

        unless @user_target.update(edit_params)
            flash.now.alert = ["Failed to save user for the following reasons"].concat(
                @user_target.get_errors
            )
            return render :edit, status: :unprocessable_entity
        end

        @user_target.update(confirmed_at: Time.now) if edit_params[:confirmed] && !was_verified

        if edit_params[:email] != email_before || (!@user_target.verified? && was_verified)
            @user_target.update(confirmed: false, confirmed_at: nil)
            @user_target.send_verification_email
            flash.notice = "Saved user and verification E-mail was sent"
        else
            flash.notice = "Saved user"
        end
        redirect_to admin_user_edit_path(@user_target.username)
    end

    def ban_form
        @user_target = User.find_by(username: params[:username])
    end

    def ban
        User.find_by(username: params[:username]).update ban_params
        flash.notice = "User banned"
        redirect_to admin_user_edit_path
    end

    def unban
        User.find_by(username: params[:username]).update banned: false
        flash.notice = "User unbanned"
        redirect_to admin_user_edit_path
    end

    def ban_ip
        return redirect_to params[:return], notice: "IP is already banned" if BannedIp.find_by(ip: ban_ip_params[:ip]).present?

        BannedIp.create ban_ip_params
        redirect_to params[:return], notice: "IP #{ban_ip_params[:ip]} was banned"
    end

    def unban_ip
        return redirect_to params[:return], notice: "IP was not banned" unless BannedIp.find_by(ip: params[:ip]).present?

        BannedIp.find_by(ip: params[:ip]).destroy
        redirect_to params[:return], notice: "IP #{params[:ip]} was unbanned"
    end

    def destroy_token
        @user_target = User.find_by(username: params[:username])
        @token = @user_target.signed_id purpose: :destroy_user, expires_in: 1.day
    end

    def destroy
        user = User.find_signed params[:destroy_token], purpose: :destroy_user

        if user.present?
            user.destroy
            flash.notice = "User deleted"
        else
            flash.alert = "Could not delete user. Retry again later"
        end
        redirect_to admin_users_path
    end

    def send_verification
        user = User.find_by(username: params[:username])
        sent = user.send_verification_email
        notice = sent ? "Verification E-mail sent to user (#{user.email})" : "Verification E-mail wasn't sent because either the user is already verified or something went wrong"
        redirect_to admin_user_edit_path(user.username), notice:
    end

    def send_password_reset
        user = User.find_by(username: params[:username])
        user.send_reset_password_email
        redirect_to admin_user_edit_path(user.username), notice: "Password reset E-mail sent to user (#{user.email})"
    end

    def prepare_email
        @user_target = User.find_by(username: params[:username])
    end

    def send_email
        user = User.find_by(username: params[:username])
        UserMailer
            .with(email: user.email, subject: params[:subject], body: params[:body])
            .email_to_user
            .deliver_later
        redirect_to admin_user_edit_path(user.username), notice: "E-mail sent to user (#{user.email})"
    end

    private

    def edit_params
        params.require(:user).permit(
            :username,
            :email,
            :unconfirmed_email,
            :role,
            :confirmed
        )
    end

    def ban_params
        params.require(:user).permit(:banned, :ban_reason)
    end

    def ban_ip_params
        params.require(:banned_ip).permit(:ip, :reason)
    end

    def find_ban_data
        @referenced_ips_banned = [@user_target&.current_sign_in_ip, @user_target&.last_sign_in_ip]
        @referenced_ips_banned = @referenced_ips_banned.uniq.map { |ip| BannedIp.find_by(ip:) }.filter(&:present?)
        @ip_ban_reasons = @referenced_ips_banned.map(&:reason)
        @referenced_ips_banned.map!(&:ip)
    end
end

app/controllers/user/password_controller.rb
class User::PasswordController < ApplicationController
    before_action { setup_locale "user.password" }

    def reset
        redirect_to user_path, notice: t("user.sessions.new.already_logged_in") if logged_in?
    end

    def send_email
        override_action "reset"

        user = User.find_by_username_or_email(params[:username])

        unless user.present?
            flash.now.alert = tp("wrong_username")
            return render :reset, status: 401
        end

        user.send_reset_password_email
        redirect_to root_path, notice: tp("sent_email")
    end

    def edit
        user =
            User.find_signed params[:password_reset_token], purpose: :reset_password
        return if user.present?

        redirect_to root_path, alert: tp("invalid_link")
    end

    def update
        override_action "edit"

        user = User.find_signed params[:password_reset_token], purpose: :reset_password
        return redirect_to root_path, alert: tp("invalid_link") unless user.present?

        if user.update(
            password: params[:password],
            password_confirmation: params[:password_confirmation]
        )
            session[:user_id] = user.id

            user.sign_in request.remote_ip

            redirect_to user_path, notice: tp("changed_password")
        else
            flash.now.alert = user.get_errors
            render :edit, status: :unprocessable_entity
        end
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
    def display_field(field)
        field.present? ? field : "Not defined"
    end
end

app/helpers/api/user_helper.rb
module Api::UserHelper
end

app/helpers/user/password_helper.rb
module User::PasswordHelper
end

app/helpers/user/sessions_helper.rb
module User::SessionsHelper
end

app/helpers/user/user_helper.rb
module User::UserHelper
end

app/helpers/user/verification_helper.rb
module User::VerificationHelper
end

app/views/admin/users/_delete_button.html.erb
<%= button_to "Delete", admin_user_delete_path(username: user.username, destroy_token: token), method: :delete, class: "btn-danger", data: { admin__destroy_user_target: "button", action: "admin--destroy-user#click" } %>

app/views/admin/users/ban_form.html.erb
<h1>Ban user <%= @user_target.username %></h1>

<%= form_with model: @user_target, url: admin_user_ban_path, method: :patch do |form| %>
    <%= form.text_field :banned, value: 1, hidden: true %>
    <div class="flex flex-col gap-2">
        <%= form.text_area :ban_reason, placeholder: "Reason for the ban", class: "rounded grow normal-border normal-background focus:ring-0 focus:border-gray-300 dark:focus:border-gray-700" %>
        <div class="flex flex-col sm:flex-row gap-2">
            <%= form.submit "Ban!", data: { turbo_confirm: "Are you sure you want to ban #{@user_target.username}?" }, class: "btn-danger-sleek grow basis-0" %>
            <%= link_to "Cancel", admin_user_edit_path, class: "btn-secondary-sleek grow basis-0" %>
        </div>
    </div>
<% end %>

app/views/admin/users/ban_ip_form.html.erb
<h1>Ban IP</h1>

<%= form_with model: BannedIp.new, url: admin_ban_ip_path(return: params[:return]), method: :put do |form| %>
    <div class="flex flex-col gap-2">
        <%= form.text_field :ip, value: params[:ip], placeholder: "IP address to ban", class: "normal-border normal-background rounded focus:ring-0 focus:border-gray-300 dark:focus:border-gray-700" %>
        <%= form.text_area :reason, placeholder: "Ban reason", class: "normal-border normal-background rounded rocus:ring-0 focus:border-gray-300 dark:focus:border-gray-700" %>
        <div class="flex gap-2">
            <%= form.submit "Ban!", class: "btn-danger-sleek grow basis-0", data: { turbo_confirm: "Are you sure you want to ban #{params[:ip]}?" } %>
            <%= link_to "Cancel", params[:return], class: "btn-secondary-sleek grow basis-0" %>
        </div>
    </div>
<% end %>

app/views/admin/users/destroy_token.html.erb
<h1>Are you sure you want to delete this account?</h1>
<h4>After deletion the account cannot be recovered!</h4>
<h4>Click all the three buttons to confirm</h4>

<div class="flex flex-col gap-40">
    <%= link_to "Cancel", admin_user_edit_path(@user_target.username), class: "grow btn-success text-lg" %>
    <div id="delete-button-container" data-controller="admin--destroy-user" class="flex justify-between">
        <% 3.times do %>
            <%= render partial: "delete_button", locals: {user: @user_target, token: @token} %>
        <% end %>
    </div>
</div>

app/views/admin/users/edit.html.erb
<div class="flex gap-2 justify-center">
    <h1><%= @user_target.username %></h1>
    <%= image_tag @user_target.avatar_url, class: "h-16 w-16 rounded-full border-4 border-blue-600" %>
</div>

<div class="grid grid-flow-row md:grid-cols-2 xl:grid-cols-3 gap-2 mt-2">
    <div><strong>E-Mail: </strong><%= @user_target.email %></div>
    <div><strong>Unconfirmed E-Mail: </strong><%= display_field(@user_target.unconfirmed_email) %></div>
    <div><strong>E-Mail confirmed: </strong><%= @user_target.confirmed %></div>
    <% if @user_target.confirmed %>
        <div title="<%= @user_target.confirmed_at %>"><strong>E-Mail confirmed </strong><%= distance_of_time_in_words_to_now(@user_target.confirmed_at, locale: :en) %> ago</div>
    <% end %>
    <div><strong>Role: </strong><%= t "general.roles.#{@user_target.role}", locale: :en %></div>
    <div><strong>End user agreement: </strong><%= @user_target.agb %></div>
    <div><strong>Sign in count: </strong><%= @user_target.sign_in_count %></div>
    <div title="<%= @user_target.current_sign_in_at %>"><strong>Current sign in </strong><%= distance_of_time_in_words_to_now(@user_target.current_sign_in_at, locale: :en) %> ago</div>
    <div><strong>Current sign in IP: </strong> <%= @user_target.current_sign_in_ip %></div>
    <div><strong>Current sign in from: </strong><%= display_field(@current_sign_in_location) %></div>
    <% if @user_target.last_sign_in_at.present? %>
        <div title="<%= @user_target.last_sign_in_at %>"><strong>Last sign in </strong><%= distance_of_time_in_words_to_now(@user_target.last_sign_in_at, locale: :en) %> ago</div>
        <div><strong>Last sign in IP: </strong><%= @user_target.last_sign_in_ip %></div>
        <div><strong>Last sign in from: </strong><%= display_field(@last_sign_in_location) %></div>
    <% end %>
</div>

<hr class="my-3">

<div class="grid grid-flow-row md:grid-cols-2 xl:grid-cols-3 gap-2">
    <div><strong>Number of Quizzes created: </strong><%= @user_target.quizzes.count %></div>
    <div><strong>Number of Translations: </strong><%= @user_target.quizzes.map {|q| q.translations.count}.sum %></div>
    <div><strong>Number of favorite Quizzes: </strong><%= @user_target.favorite_quizzes.count %></div>
    <div><strong>Number of scores: </strong><%= @user_target.scores.count %></div>
    <div><strong>Bugs reported: </strong><%= @user_target.bug_reports.count %></div>
    <div><strong>Bugs smashed: </strong><%= @user_target.bugs_smashed %></div>
</div>

<hr class="my-3">

<div class="mb-3 grid grid-flow-row md:grid-cols-2 gap-2">
    <div><strong>User banned: </strong><%= @user_target.banned %></div>
    <% if @user_target.banned %>
        <div><strong>Ban reason: </strong><%= display_field(@user_target.ban_reason) %></div>
    <% end %>
    <div><strong>Referenced IPs banned: </strong>
        <% if @referenced_ips_banned.count.positive? %>
            <%= @referenced_ips_banned.join(", ") %>
        <% else %>
            None
        <% end %>
    </div>
    <% if @ip_ban_reasons.count.positive? %>
        <div><strong>IP ban reasons: </strong><%= @ip_ban_reasons.map { |reason| display_field(reason) }.join(", ") %></div>
    <% end %>
</div>

<div class="grid grid-flow-row md:grid-cols-2 gap-2">
    <% unless @user_target.banned %>
        <%= link_to "Ban user",  admin_user_ban_path, class: "btn-secondary-sleek grow" %>
    <% else %>
        <%= link_to "Unban user", admin_user_unban_path, data: { turbo_method: :patch, turbo_confirm: "Are you sure you want to unban #{@user_target.username} for reason #{@user_target.ban_reason}" }, class: "btn-success-sleek grow"%>
    <% end %>

    <% unless BannedIp.find_by(ip: @user_target.current_sign_in_ip).present? %>
        <%= link_to "Ban IP #{@user_target.current_sign_in_ip}", admin_ban_ip_path(ip: @user_target.current_sign_in_ip, return: request.path), class: "btn-secondary-sleek" %>
    <% else %>
        <%= link_to "Unban IP #{@user_target.current_sign_in_ip}", admin_ban_ip_path(ip: @user_target.current_sign_in_ip, return: request.path), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to unban IP #{@user_target.current_sign_in_ip} for reason #{@ip_ban_reasons.first}" }, class: "btn-success-sleek" %>
    <% end %>
</div>

<hr class="my-3">

<%= form_with model: @user_target, url: admin_user_edit_path(@user_target.username) do |form| %>
    <div class="md:grid space-y-2 md:space-y-0 gap-2 grid-flow-row grid-cols-2">
        <div class="rounded border border-gray-300 divide-x divide-gray-300 dark:border-gray-700 dark:divide-gray-700 flex">
            <%= form.label :username, "Username", class: "p-2 rounded-s bg-gray-200 dark:bg-gray-800" %>
            <%= form.text_field :username, class: "grow rounded-e border-0 border-s focus:ring-0 overflow-hidden dark:bg-gray-900" %>
        </div>
        <div class="rounded border border-gray-300 divide-x divide-gray-300 dark:border-gray-700 dark:divide-gray-700 flex">
            <%= form.label :email, "E-mail", class: "text-nowrap p-2 rounded-s bg-gray-200 dark:bg-gray-800" %>
            <%= form.text_field :email, class: "grow rounded-e border-0 border-s focus:ring-0 overflow-hidden dark:bg-gray-900" %>
        </div>
        <div class="rounded border border-gray-300 divide-x divide-gray-300 dark:border-gray-700 dark:divide-gray-700 flex">
            <%= form.label :role, "Role", class: "p-2 rounded-s bg-gray-200 dark:bg-gray-800" %>
            <%= form.select :role, User::ROLES.map { |r| [t("general.roles.#{r}", locale: :en), r] }, {}, { class: "grow rounded-e border-0 border-s focus:ring-0 cursor-pointer dark:bg-gray-900" } %>
        </div>
        <div class="rounded border border-gray-300 divide-x divide-gray-300 dark:border-gray-700 dark:divide-gray-700 flex">
            <%= form.label :confirmed, "E-mail confirmed", class: "text-nowrap p-2 rounded-s bg-gray-200 dark:bg-gray-800" %>
            <%= form.select :confirmed, [["Yes", true], ["No", false]], {}, { class: "grow rounded-e border-0 border-s focus:ring-0 cursor-pointer dark:bg-gray-900" } %>
        </div>
        <div class="flex"><%= form.submit "Save", class: "btn-success-sleek grow" %></div>
        <div class="flex"><%= link_to "Cancel", admin_users_path, class: "btn-secondary-sleek grow" %></div>
        <br class="md:hidden">
        <div class="flex"><%= link_to "Send E-mail", admin_user_send_email_path(@user_target.username), class: "btn-primary-sleek grow" %></div>
        <div class="flex"><%= link_to "Send verification E-mail", admin_user_send_verification_path(@user_target.username), class: "btn-primary-sleek grow" %></div>
        <div class="flex"><%= link_to "Send password reset E-mail", admin_user_send_password_reset_path(@user_target.username), class: "btn-primary-sleek grow" %></div>
        <br class="md:hidden">
        <div class="flex"><%= link_to "Delete account", admin_user_delete_path(@user_target.username), class: "btn-danger-sleek grow" %></div>
    </div>
<% end %>

app/views/admin/users/prepare_email.html.erb
<h1>Send E-mail</h1>
<h4>Send an E-mail to the user <%= @user_target.username %> (<%= @user_target.email %>)</h4>

<%= form_with url: admin_user_send_email_path(@user_target.username) do |form| %>
    <div class="flex flex-col gap-2">
        <div class="flex rounded border border-gray-300 divide-x divide-gray-300 dark:border-gray-700 dark:divide-gray-700">
            <%= form.label :subject, "Subject", class: "p-2 rounded-s bg-gray-100 dark:bg-gray-800" %>
            <%= form.text_field :subject, class: "grow rounded-e border-0 border-s focus:ring-0 dark:bg-transparent" %>
        </div>
        <%= form.text_area :body, placeholder: "E-mail body", rows: 10, class: "rounded border-gray-300 focus:ring-teal-700 focus:border-teal-700 dark:border-gray-700 dark:bg-transparent" %>
        <%= form.submit "Send", class: "btn-success text-lg" %>
    </div>
<% end %>